Iterative algorithms to solve a system of linear equations:

* Gauss-Seidel method
* Jacobi method

In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

In [2]:
class Counter:
    """Class to count iterations taken by each algorithm"""

    def __init__(self, limit=500):
        self.iter = 0
        self.limit = limit # Sets limit for loops in each algorithm
        
    def count(self):
        self.iter += 1
        
    def get_count(self):
        return(self.iter)
    
    def reset_count(self):
        self.iter = 0

# Jacobi

$X^{k} = D^{-1}b - D^{-1}(L + U)X^{k - 1}$

In [3]:
#Jacobi Alg.
def jacobi(A, b, counter=Counter()):
    """
    Solves system of linear equations numerically using Jacobi's alg
    
    Parameters:
    ==========
    A: Coefficients matrix
    b: Solution of equations vector
    
    Returns: "x_new" the roots vector
    """
    
    b = b.reshape((len(A), 1))
    x_old = np.zeros_like(b) #initial guess
    
    L = np.tril(A) #lower triangular
    U = np.triu(A) #Upper triangular
    D = np.diag(A) #diagonal
    LplusU = L + U - 2* np.diag(D)
    D = D.reshape(b.shape)
    
    
    check = False
    eps = 1e-8 #tolerance
    
    while check == False and counter.get_count() < counter.limit:
        x_new = (b - (LplusU) @ x_old) / D #x_new has a new address
        check = (linalg.norm(x_new - x_old, 2) / linalg.norm(x_new, 2)) < eps
        x_old = x_new #copy memory address
        counter.count()
        
    return x_new

# Gauss Seidel

$X^{k} = (D + L)^{-1}(b-UX^{k-1})$

In [4]:
#Gauss Seidel Alg.
def seidel(A, b, counter=Counter()):
    """
    Solves system of linear equations numerically using Gauss Seidel's alg
    
    Parameters:
    ==========
    A: Coefficients matrix
    b: Solution of equations vector
    
    Returns: "x_new" the roots vector
    """
    
    b = b.reshape((len(A), 1))
    x_old = np.zeros_like(b) #initial guess
    
    LD = np.tril(A) #Lower triangular
    U = A - LD # Upper without diagonal
    LD_inv = linalg.inv(LD)
    
    check = False
    eps = 1e-8 #tolerance
   
    while check == False and counter.get_count() < counter.limit:
        x_new = LD_inv @ (b - U @ x_old) #x_new has a new address
        check = (linalg.norm(x_new - x_old, 2) / linalg.norm(x_new, 2)) < eps
        x_old = x_new #copy memory address
        counter.count()
        
    return x_new

# Power method

In [5]:
# Power method
def power_method(A, counter=Counter()):
    """
    Power method Algorithm to solve for the dominant eigenvector and its eigenvalue
    
    Parameters:
    ===========
    A: Coefficient matrix, whose eigenvalues are required
    
    Returns:
    ========
    eig_v: The dominant eigenvalue
    x_new: Dominant eigenvector
    """
    x_old = np.random.randint(0, 20, (A.shape[0], 1)) #Initial guess of eigenvector
    check = False
    eig_v = 0
    eps = 1e-8 #Tolerance
    
    while check == False and counter.get_count() < counter.limit:
        x_new = A @ x_old
        eig_v = np.max(x_new) #Uniform norm "Infinity norm"
        x_new = x_new / eig_v #New eigenvector 
        check = (linalg.norm(x_new - x_old, 2) / linalg.norm(x_new, 2)) < eps
        x_old = x_new
        counter.count()
    
    return eig_v, x_new

# Homework 3
## Question 1
### System modeling
$4p_1 - p_2 - p_3 = 0$<br>


$5p_2 - p_1 - p_3 - p_4 - p_5= 0$<br>


$5p_3 - p_1 - p_2 - p_5 - p_6 = 0$<br>


$5p_4 - p_2 - p_5 - p_7 - p_8 = 0$<br>


$6p_5 - p_2 - p_3 - p_4 - p_6 - p_8 - p_9 = 0$<br>


$5p_6 - p_3 - p_5 - p_9 - p_{10} = 0$<br>


$4p_7 - p_4 - p_8= 1$<br>


$5p_8 - p_4 - p_5 - p_7 - p_9=1$<br>


$5p_9 - p_5 - p_6 - p_8 - p_{10} = 1$<br>


$4p_{10} - p_6 - p_9=1$<br>

In [6]:
A = np.array([
    [4, -1, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 5, -1, -1, -1, 0, 0, 0, 0, 0],
    [-1, -1, 5, 0, -1, -1, 0, 0, 0, 0],
    [0, -1, 0, 5, -1, 0, -1, -1, 0, 0],
    [0, -1, -1, -1, 6, -1, 0, -1, -1, 0],
    [0, 0, -1, 0, -1, 5, 0, 0, -1, -1],
    [0, 0, 0, -1, 0, 0, 4, -1, 0, 0],
    [0, 0, 0, -1, -1, 0, -1, 5, -1, 0],
    [0, 0, 0, 0, -1, -1, 0, -1, 5, -1],
    [0, 0, 0, 0, 0, -1, 0, 0, -1, 4]])

b = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])
counter = Counter()
x = jacobi(A, b, counter)
print("Jacobi roots:\nIn ", counter.get_count(), "Iterations\n", x, "\n")
counter.reset_count()
x = seidel(A, b, counter)
print("Gauss Seidel roots:\nIn ", counter.get_count(), "Iterations\n", x, "\n\n")

Jacobi roots:
In  70 Iterations
 [[0.09019607]
 [0.18039214]
 [0.18039214]
 [0.2980392 ]
 [0.33333332]
 [0.2980392 ]
 [0.45490195]
 [0.52156861]
 [0.52156861]
 [0.45490195]] 

Gauss Seidel roots:
In  38 Iterations
 [[0.09019607]
 [0.18039215]
 [0.18039215]
 [0.29803921]
 [0.33333333]
 [0.29803921]
 [0.45490196]
 [0.52156862]
 [0.52156862]
 [0.45490196]] 




## Question 2

In [7]:
A1 = np.array([
    [0, 1, 2],
    [0.5, 0, 0],
    [0, 0.25, 0]])

A2 = np.array([
    [0, 6, 8],
    [0.5, 0, 0], 
    [0, 0.5, 0]])

#Question 1
print("Question 1:\nPower Method:")
print("=" * len("Power Method"))
l, v = power_method(A1)
print("Eigenvalue:\n", l, "\n")
print("Eigenvector:\n", v, "\n\n")

print("Check:")
print("=" * len("Check"))
print("Left hand side A @ v:\n", A1 @ v, "\n") #Transformation matrix (dot) Eigenvector
print("Right hand side: l * v\n", l * v, "\n\n") #Eigenvalue * Eigenvector
print("-" * 50, "\n")

#Question 2
print("Question 2:\nPower Method:")
print("=" * len("Power Method"))
l, v = power_method(A2)
print("Eigenvalue:\n", l, "\n")
print("Eigenvector:\n", v, "\n\n")

print("Check:")
print("=" * len("Check"))
print("Left hand side: A @ v\n", A2 @ v, "\n")
print("Right hand side: l * v\n", l * v, "\n\n")

Question 1:
Power Method:
Eigenvalue:
 0.8846461812138321 

Eigenvector:
 [[1.        ]
 [0.56519771]
 [0.15972423]] 


Check:
=====
Left hand side A @ v:
 [[0.88464617]
 [0.5       ]
 [0.14129943]] 

Right hand side: l * v
 [[0.88464618]
 [0.5       ]
 [0.14129943]] 


-------------------------------------------------- 

Question 2:
Power Method:
Eigenvalue:
 1.9999999742797248 

Eigenvector:
 [[1.    ]
 [0.25  ]
 [0.0625]] 


Check:
=====
Left hand side: A @ v
 [[2.00000001]
 [0.5       ]
 [0.125     ]] 

Right hand side: l * v
 [[1.99999997]
 [0.5       ]
 [0.125     ]] 


